require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - db/schema.rb

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Metrics/BlockLength:
  Exclude: 
    - 'spec/**/*'

Rails/RequestReferer:
  EnforcedStyle: referrer

RSpec/ExampleLength:
  Max: 10

RSpec/HookArgument:
  Enabled: false

RSpec/ImplicitSubject:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleExpectations:
  Exclude:
    - spec/views/**/*

RSpec/NestedGroups:
  Enabled: false

Style/DoubleNegation:
  Enabled: false
