require:
  - rubocop-performance
  - rubocop-rails
  - rubocop-rspec
AllCops:
  Exclude:
    - db/schema.rb

Layout/EmptyLineAfterGuardClause:
  Enabled: false

Rails/RequestReferer:
  EnforcedStyle: referrer
  