 require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/hunter_backstories", type: :request do
  # HunterBackstory. As you add validations to HunterBackstory, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      HunterBackstory.create! valid_attributes
      get hunter_backstories_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      hunter_backstory = HunterBackstory.create! valid_attributes
      get hunter_backstory_url(hunter_backstory)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_hunter_backstory_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "render a successful response" do
      hunter_backstory = HunterBackstory.create! valid_attributes
      get edit_hunter_backstory_url(hunter_backstory)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new HunterBackstory" do
        expect {
          post hunter_backstories_url, params: { hunter_backstory: valid_attributes }
        }.to change(HunterBackstory, :count).by(1)
      end

      it "redirects to the created hunter_backstory" do
        post hunter_backstories_url, params: { hunter_backstory: valid_attributes }
        expect(response).to redirect_to(hunter_backstory_url(HunterBackstory.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new HunterBackstory" do
        expect {
          post hunter_backstories_url, params: { hunter_backstory: invalid_attributes }
        }.to change(HunterBackstory, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post hunter_backstories_url, params: { hunter_backstory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested hunter_backstory" do
        hunter_backstory = HunterBackstory.create! valid_attributes
        patch hunter_backstory_url(hunter_backstory), params: { hunter_backstory: new_attributes }
        hunter_backstory.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the hunter_backstory" do
        hunter_backstory = HunterBackstory.create! valid_attributes
        patch hunter_backstory_url(hunter_backstory), params: { hunter_backstory: new_attributes }
        hunter_backstory.reload
        expect(response).to redirect_to(hunter_backstory_url(hunter_backstory))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        hunter_backstory = HunterBackstory.create! valid_attributes
        patch hunter_backstory_url(hunter_backstory), params: { hunter_backstory: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested hunter_backstory" do
      hunter_backstory = HunterBackstory.create! valid_attributes
      expect {
        delete hunter_backstory_url(hunter_backstory)
      }.to change(HunterBackstory, :count).by(-1)
    end

    it "redirects to the hunter_backstories list" do
      hunter_backstory = HunterBackstory.create! valid_attributes
      delete hunter_backstory_url(hunter_backstory)
      expect(response).to redirect_to(hunter_backstories_url)
    end
  end
end
